// generated by newgenasym  Fri Mar 31 14:01:22 2006


module p4_3ghz_sym (\a10* , \a11* , \a12* , \a13* , \a14* , \a15* , \a16* , \a17* , \a18* , \a19* ,
        \a20* , \a20m* , \a21* , \a22* , \a23* , \a24* , \a25* , \a26* , \a27* , \a28* ,
        \a29* , \a3* , \a30* , \a31* , \a32* , \a33* , \a34* , \a35* , \a4* , \a5* , \a6* ,
        \a7* , \a8* , \a9* , \ads* , \adstb0* , \adstb1* , \ap0* , \ap1* , bclk0,
        bclk1, \binit* , \bnr* , bpm, \bpri* , \br0* , bsel0, bsel1, comp0,
        comp1, \d0* , \d1* , \d10* , \d11* , \d12* , \d13* , \d14* , \d15* , \d16* , \d17* ,
        \d18* , \d19* , \d2* , \d20* , \d21* , \d22* , \d23* , \d24* , \d25* , \d26* , \d27* ,
        \d28* , \d29* , \d3* , \d30* , \d31* , \d32* , \d33* , \d34* , \d35* , \d36* , \d37* ,
        \d38* , \d39* , \d4* , \d40* , \d41* , \d42* , \d43* , \d44* , \d45* , \d46* , \d47* ,
        \d48* , \d49* , \d5* , \d50* , \d51* , \d52* , \d53* , \d54* , \d55* , \d56* , \d57* ,
        \d58* , \d59* , \d6* , \d60* , \d61* , \d62* , \d63* , \d7* , \d8* , \d9* , \dbi0* ,
        \dbi1* , \dbi2* , \dbi3* , \dbr* , \dbsy* , \defer* , \dp0* , \dp1* , \dp2* ,
        \dp3* , \drdy* , \dstbn0* , \dstbn1* , \dstbn2* , \dstbn3* , \dstbp0* ,
        \dstbp1* , \dstbp2* , \dstbp3* , \ferr* , gtlref0, gtlref1, gtlref2,
        gtlref3, \hit* , \hitm* , \ierr* , \ignne* , \init* , itp_clk0,
        itp_clk1, itpclkout0, itpclkout1, lint0, lint1, \lock* ,
        \mcerr* , p100, \prochot* , pwrgood, \req0* , \req1* , \req2* , \req3* ,
        \req4* , \reset* , \rs0* , \rs1* , \rs2* , \rsp* , \sktocc* , \slp* , \smi* ,
        \stpclk* , tck, tdi, tdo, testhi0, testhi1, testhi10, testhi11,
        testhi12, testhi2, testhi3, testhi4, testhi5, testhi8,
        testhi9, \thermtrip* , tms, \trdy* , \trst* , vccsense, vccvid,
        vid0, vid1, vid2, vid3, vid4, vsssense);
    inout \a10* ;
    inout \a11* ;
    inout \a12* ;
    inout \a13* ;
    inout \a14* ;
    inout \a15* ;
    inout \a16* ;
    inout \a17* ;
    inout \a18* ;
    inout \a19* ;
    inout \a20* ;
    input \a20m* ;
    inout \a21* ;
    inout \a22* ;
    inout \a23* ;
    inout \a24* ;
    inout \a25* ;
    inout \a26* ;
    inout \a27* ;
    inout \a28* ;
    inout \a29* ;
    inout \a3* ;
    inout \a30* ;
    inout \a31* ;
    inout \a32* ;
    inout \a33* ;
    inout \a34* ;
    inout \a35* ;
    inout \a4* ;
    inout \a5* ;
    inout \a6* ;
    inout \a7* ;
    inout \a8* ;
    inout \a9* ;
    inout \ads* ;
    inout \adstb0* ;
    inout \adstb1* ;
    inout \ap0* ;
    inout \ap1* ;
    input bclk0;
    input bclk1;
    inout \binit* ;
    inout \bnr* ;
    inout [6:1] bpm;
    input \bpri* ;
    inout \br0* ;
    output bsel0;
    output bsel1;
    inout comp0;
    inout comp1;
    inout \d0* ;
    inout \d1* ;
    inout \d10* ;
    inout \d11* ;
    inout \d12* ;
    inout \d13* ;
    inout \d14* ;
    inout \d15* ;
    inout \d16* ;
    inout \d17* ;
    inout \d18* ;
    inout \d19* ;
    inout \d2* ;
    inout \d20* ;
    inout \d21* ;
    inout \d22* ;
    inout \d23* ;
    inout \d24* ;
    inout \d25* ;
    inout \d26* ;
    inout \d27* ;
    inout \d28* ;
    inout \d29* ;
    inout \d3* ;
    inout \d30* ;
    inout \d31* ;
    inout \d32* ;
    inout \d33* ;
    inout \d34* ;
    inout \d35* ;
    inout \d36* ;
    inout \d37* ;
    inout \d38* ;
    inout \d39* ;
    inout \d4* ;
    inout \d40* ;
    inout \d41* ;
    inout \d42* ;
    inout \d43* ;
    inout \d44* ;
    inout \d45* ;
    inout \d46* ;
    inout \d47* ;
    inout \d48* ;
    inout \d49* ;
    inout \d5* ;
    inout \d50* ;
    inout \d51* ;
    inout \d52* ;
    inout \d53* ;
    inout \d54* ;
    inout \d55* ;
    inout \d56* ;
    inout \d57* ;
    inout \d58* ;
    inout \d59* ;
    inout \d6* ;
    inout \d60* ;
    inout \d61* ;
    inout \d62* ;
    inout \d63* ;
    inout \d7* ;
    inout \d8* ;
    inout \d9* ;
    inout \dbi0* ;
    inout \dbi1* ;
    inout \dbi2* ;
    inout \dbi3* ;
    output \dbr* ;
    inout \dbsy* ;
    input \defer* ;
    inout \dp0* ;
    inout \dp1* ;
    inout \dp2* ;
    inout \dp3* ;
    inout \drdy* ;
    inout \dstbn0* ;
    inout \dstbn1* ;
    inout \dstbn2* ;
    inout \dstbn3* ;
    inout \dstbp0* ;
    inout \dstbp1* ;
    inout \dstbp2* ;
    inout \dstbp3* ;
    output \ferr* ;
    input gtlref0;
    input gtlref1;
    input gtlref2;
    input gtlref3;
    inout \hit* ;
    inout \hitm* ;
    output \ierr* ;
    input \ignne* ;
    input \init* ;
    input itp_clk0;
    input itp_clk1;
    output itpclkout0;
    output itpclkout1;
    input lint0;
    input lint1;
    inout \lock* ;
    inout \mcerr* ;
    input p100;
    inout \prochot* ;
    input pwrgood;
    inout \req0* ;
    inout \req1* ;
    inout \req2* ;
    inout \req3* ;
    inout \req4* ;
    input \reset* ;
    input \rs0* ;
    input \rs1* ;
    input \rs2* ;
    input \rsp* ;
    output \sktocc* ;
    input \slp* ;
    input \smi* ;
    input \stpclk* ;
    input tck;
    input tdi;
    output tdo;
    input testhi0;
    input testhi1;
    input testhi10;
    input testhi11;
    input testhi12;
    input testhi2;
    input testhi3;
    input testhi4;
    input testhi5;
    input testhi8;
    input testhi9;
    output \thermtrip* ;
    input tms;
    input \trdy* ;
    input \trst* ;
    output vccsense;
    input vccvid;
    output vid0;
    output vid1;
    output vid2;
    output vid3;
    output vid4;
    output vsssense;


    initial
        begin
        end

endmodule
