// generated by newgenasym  Thu May 08 07:05:36 2003


module for_baselining (a1, a2, a3, a4, b1, b2, b3, b4, vcc);
    input a1;
    input a2;
    input a3;
    input a4;
    output b1;
    output b2;
    output b3;
    output b4;
    input vcc;


    initial
        begin
        end

endmodule
