-- generated by newgenasym Thu May 08 07:05:37 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity for_baselining is
    port (    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        IN     STD_LOGIC;    
	B1:        OUT    STD_LOGIC;    
	B2:        OUT    STD_LOGIC;    
	B3:        OUT    STD_LOGIC;    
	B4:        OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end for_baselining;
