// generated by newgenasym  Sun Sep 11 06:34:05 2011


module mypart (a1, a2, a3, a4, b, nc, vcc);
    input a1;
    input a2;
    input a3;
    input a4;
    output [4:1] b;
    inout [4:0] nc;
    input vcc;


    initial
        begin
        end

endmodule
