-- generated by newgenasym Sun Sep 11 06:34:05 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mypart is
    port (    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        IN     STD_LOGIC;    
	B:         OUT    STD_LOGIC_VECTOR (4 DOWNTO 1);    
	NC:        INOUT  STD_LOGIC_VECTOR (4 DOWNTO 0);    
	VCC:       IN     STD_LOGIC);
end mypart;
