// generated by newgenasym  Sat Sep 10 23:50:44 2011


module n87c196nt (a16, a17, a18, a19, ach4, ach5, ach6, ach7, ad10, ad11, ad12,
        ad13, ad14, ad15, ad8, ad9, \breq* , buswidth, clkout, \ea* , epa0,
        epa1, epa2, epa3, epa4, epa5, epa6, epa7, epa8, epa9, \hlda* ,
        \hold* , \intout* , nmi, \p2.0 , \p2.1 , \p2.2 , \p5.0* , \p5.1 , \p5.2* ,
        \p5.3* , \p5.4 , \p5.5* , \p5.6 , \p6.2 , \p6.3 , \p6.4 , \p6.5 , \p6.6 , \p6.7 ,
        \reset* , slp0, slp1, slp2, slp3, slp4, slp5, slp6, slp7, xtal1,
        xtal2);
    inout a16;
    inout a17;
    inout a18;
    inout a19;
    input ach4;
    input ach5;
    input ach6;
    input ach7;
    inout ad10;
    inout ad11;
    inout ad12;
    inout ad13;
    inout ad14;
    inout ad15;
    inout ad8;
    inout ad9;
    output \breq* ;
    input buswidth;
    output clkout;
    input \ea* ;
    inout epa0;
    inout epa1;
    inout epa2;
    inout epa3;
    inout epa4;
    inout epa5;
    inout epa6;
    inout epa7;
    inout epa8;
    inout epa9;
    output \hlda* ;
    input \hold* ;
    output \intout* ;
    input nmi;
    output \p2.0 ;
    input \p2.1 ;
    input \p2.2 ;
    output \p5.0* ;
    output \p5.1 ;
    output \p5.2* ;
    output \p5.3* ;
    inout \p5.4 ;
    output \p5.5* ;
    input \p5.6 ;
    inout \p6.2 ;
    inout \p6.3 ;
    inout \p6.4 ;
    inout \p6.5 ;
    inout \p6.6 ;
    inout \p6.7 ;
    input \reset* ;
    inout slp0;
    inout slp1;
    inout slp2;
    inout slp3;
    inout slp4;
    inout slp5;
    inout slp6;
    inout slp7;
    input xtal1;
    output xtal2;


    initial
        begin
        end

endmodule
