// generated by newgenasym  Thu May 08 10:58:12 2003


module part_for_interface_comparision (a, b, c, d, m);
    input a;
    input b;
    output c;
    output d;
    input m;


    initial
        begin
        end

endmodule
