-- generated by newgenasym Thu May 08 10:58:12 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity part_for_interface_comparision is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	C:         OUT    STD_LOGIC;    
	D:         OUT    STD_LOGIC;    
	M:         IN     STD_LOGIC);
end part_for_interface_comparision;
