// generated by newgenasym  Tue Oct 04 10:06:51 2005


module sample_part (\pin+ , \pin- , pin1, pin10, pin11, pin12, pin13, pin2, pin3,
        pin4, pin5, pin6, pin7, pin8, pin9);
    output \pin+ ;
    output \pin- ;
    input pin1;
    input pin10;
    output pin11;
    output pin12;
    input pin13;
    output pin2;
    output pin3;
    input pin4;
    input pin5;
    input pin6;
    output pin7;
    output pin8;
    input pin9;


    initial
        begin
        end

endmodule
