-- generated by newgenasym Tue Oct 04 10:06:52 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sample_part is
    port (    
	\pin+\:    OUT    STD_LOGIC;    
	\pin-\:    OUT    STD_LOGIC;    
	PIN1:      IN     STD_LOGIC;    
	PIN10:     IN     STD_LOGIC;    
	PIN11:     OUT    STD_LOGIC;    
	PIN12:     OUT    STD_LOGIC;    
	PIN13:     IN     STD_LOGIC;    
	PIN2:      OUT    STD_LOGIC;    
	PIN3:      OUT    STD_LOGIC;    
	PIN4:      IN     STD_LOGIC;    
	PIN5:      IN     STD_LOGIC;    
	PIN6:      IN     STD_LOGIC;    
	PIN7:      OUT    STD_LOGIC;    
	PIN8:      OUT    STD_LOGIC;    
	PIN9:      IN     STD_LOGIC);
end sample_part;
